config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 
  resources :lists do 
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord

  has_many :todo_items, dependent: :destroy
  validates_presence_of :name, :duedate
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :list

  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:edit, :show, :update, :destroy]

  def index
    @lists = List.all
  end


  def new
    @list = List.new
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render 'edit'
    end
  end

  def show
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render 'new'
    end
  end

  def destroy
    @list.destroy

    redirect_to root_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :duedate, :note)
  end

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_list
  before_action :set_todo_item, except: [:create]
    
  def create
    @todo_item = @list.todo_items.create(todo_item_params)
    redirect_to @list
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @list, notice: "Todo item completed"
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def todo_item_params
    params.require(:todo_item).permit(:content)
  end 

  def set_todo_item
    @todo_item = @list.todo_items.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ToDoList', lists_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Log in', '#' %></li>
        <li><%= link_to 'Sign up', '#' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<h1 class="center">Create A New List</h1>

<div class="row col-sm-4 col-sm-offset-4">
  <% if @list.errors.presence %>
    <ul class="alert alert-warning" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <% @list.errors.each do |error, message| %>
        <li>
          <%= "#{error.capitalize} #{message}" %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>



<div class="form-horizontal">
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_for @list do |f| %>
      
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :name %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Name of List", autofocus: true %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :duedate %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :duedate, class: "form-control", placeholder: "Duedate of List" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :note %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :note, row: 10, class: "form-control", placeholder: "Note of List" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.submit class: "btn btn-success" %> 
            <%= link_to 'Cancel', root_path, class: "btn btn-warning" %>
          </div>
        </div>
      
    <% end %>
  </div>
</div>

app/views/lists/_list.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <% @lists.each do |list| %>
      <div class="list-title col-md-12">
        <%= link_to list.name.capitalize, list_path(list) %>
      </div>
      <div class="list-note col-md-12">
        <%= list.note.capitalize %>
      </div>
      <hr>
    <% end %>
    <div class="center">
      <button type="button" class="btn btn-success new_btn">
        <%= link_to "New List", new_list_path %>
      </button>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render 'form' %>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="center">Welcome to ToDoList</h1>
  <h3 class="center">In ToDoList, you can add lists on your board.<br /> Provide you details of your plan.</h3>

  <%= render 'list' %>
</div>

app/views/lists/new.html.erb
<%= render 'form' %>

app/views/lists/show.html.erb
<h1 class="center">Show Details of List</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well sh-well">
      <% if @list.duedate < Time.now %>
        <div class="list-title col-md-12">
          <%= @list.name.capitalize %>
        </div>
        
        <div class="list-note col-md-12">
          <%= simple_format(@list.note) %>
        </div>
        <hr>
        <div class="date-action">
          <%= link_to 'Back', lists_path %>
        </div>
      <% else %>
        <div class="list-title col-md-12">
          <%= @list.name.capitalize %>
        </div>
        
        <div class="list-note col-md-12">
          <%= simple_format(@list.note) %>
        </div>
        <hr>
        <div class="todo_items_wrapper">
          <%= render @list.todo_items %>
          <div class="form" %>
            <%= render 'todo_items/item_form' %>
          </div>
        </div>
        <hr>
        <div class="list-action">
          <%= link_to 'Back', lists_path %> |
          <%= link_to 'Edit', edit_list_path(@list) %> |
          <%= link_to 'Delete', list_path(@list), method: :delete,
                                data: { confirm: "Are you sure?"} %>
        </div>
        <div class="list-duedate pull-right">
          <%= @list.duedate %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/todo_items/_item_form.html.erb
<%= form_for([@list, @list.todo_items.build]) do |f| %>
  <div class="item-input">
    <%= f.text_field :content, placeholder: "New Item", autofocus: true %>
  </div>
  <div class="item-btn">
    <%= f.submit class: "btn btn-xs btn-primary" %>
  </div>
 
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
  <table class="table">
    <% if todo_item.completed_at? %>
      <div class="complete col-md-2">
        <%= link_to complete_list_todo_item_path(@list, todo_item.id),
                        method: :patch do %>
          <i style="opacity: 0.5;" class="fa fa-check"></i>
        <% end %>
                          
      </div>
      <div class="todo_item col-md-4">
        <p style="opacity: 0.5;"><strike><%= todo_item.content %></strike></p>
      </div>
      <div class="trash col-md-2">
        <%= link_to list_todo_item_path(@list, todo_item.id),
                      method: :delete, data: { confirm: "Are you sure?"} do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </div>
    <% else %>
      <div class="complete col-md-2">
        <%= link_to complete_list_todo_item_path(@list, todo_item.id),
                        method: :patch do %>
          <i class="fa fa-check"></i>
        <% end %>
      </div>
      <div class="todo_item col-md-4">
        <p><%= todo_item.content %></p>
      </div>
      <div class="trash col-md-2">
        <%= link_to list_todo_item_path(@list, todo_item.id),
                      method: :delete, data: { confirm: "Are you sure?"} do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </div>
    <% end %>
  </table>
</div>